command: docker template config
short: Modify docker template configuration
long: Modify docker template configuration
pname: docker template
plink: docker_template.yaml
cname:
- docker template config set
- docker template config view
clink:
- docker_template_config_set.yaml
- docker_template_config_view.yaml
deprecated: false
experimental: false
experimentalcli: true
kubernetes: false
swarm: false

