command: docker template config view
short: view default values for docker template
long: view default values for docker template
usage: docker template config view
pname: docker template config
plink: docker_template_config.yaml
options:
- option: format
  value_type: string
  default_value: yaml
  description: Configure the output format (json|yaml)
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
deprecated: false
experimental: false
experimentalcli: true
kubernetes: false
swarm: false

