command: docker template config set
short: set default values for docker template
long: set default values for docker template
usage: docker template config set
pname: docker template config
plink: docker_template_config.yaml
options:
- option: feedback
  value_type: bool
  default_value: "false"
  description: |
    Send anonymous feedback about usage (performance, failure status, os, version)
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: no-feedback
  value_type: bool
  default_value: "false"
  description: Don't send anonymous feedback
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: org
  value_type: string
  description: Set default organization / docker hub user
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: server
  value_type: string
  description: Set default registry server (host[:port])
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
deprecated: false
experimental: false
experimentalcli: true
kubernetes: false
swarm: false

