name: Docker Documentation
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  toc_levels: 2..3
incremental: true
permalink: pretty
safe: false
lsi: false
url: https://docs.docker.com/v17.03
keep_files: ["v1.4", "v1.5", "v1.6", "v1.7", "v1.8", "v1.9", "v1.10", "v1.11", "v1.12", "v1.13"]
exclude: ["Dockerfile", "Gemfile", "Gemfile.lock", "hooks", "_scripts", ".git", ".github", '*.gliffy', '*.snagproj', '*.plist', '*.diff']
gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-relative-links

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      defaultassignee: johndmulhausen
      enginebranch: 1.13.x
      toc_min: 2
      toc_max: 3
      tree: true
  - scope:
      path: "compose"
    values:
      assignee: "londoncalling"
  - scope:
      path: "cs-engine"
    values:
      assignee: "joaofnfernandes"
  - scope:
      path: "datacenter"
    values:
      assignee: "joaofnfernandes"
  - scope:
      path: "docker-cloud"
    values:
      assignee: "londoncalling"
  - scope:
      path: "docker-for-mac"
    values:
      assignee: "londoncalling"
  - scope:
      path: "docker-for-windows"
    values:
      assignee: "londoncalling"
  - scope:
      path: "docker-hub"
    values:
      assignee: "johndmulhausen"
  - scope:
      path: "docker-store"
    values:
      assignee: "johndmulhausen"
  - scope:
      path: "engine"
    values:
      assignee: "mistyhacks"
  - scope:
      path: "kitematic"
    values:
      assignee: "londoncalling"
  - scope:
      path: "machine"
    values:
      assignee: "londoncalling"
  - scope:
      path: "notary"
    values:
      assignee: "johndmulhausen"
  - scope:
      path: "registry"
    values:
      assignee: "joaofnfernandes"
  - scope:
      path: "swarm"
    values:
      assignee: "mistyhacks"
  - scope:
      path: "toolbox"
    values:
      assignee: "londoncalling"
  -
    scope:
      path: "datacenter"
    values:
      ucp_latest_image: "docker/ucp:2.1.4"
      dtr_latest_image: "docker/dtr:2.2.5"
  -
    scope:
      path: "datacenter/dtr/2.2"
    values:
      ucp_version: "2.1"
      dtr_version: "2.2"
      docker_image: "docker/dtr:2.2.5"
  -
    scope:
      path: "datacenter/dtr/2.1"
    values:
      hide_from_sitemap: true
      ucp_version: "2.0"
      dtr_version: "2.1"
  -
    scope:
      path: "datacenter/dtr/2.0"
    values:
      hide_from_sitemap: true
      ucp_version: "1.1"
      dtr_version: "2.0"
  -
    scope:
      path: "datacenter/ucp/2.1"
    values:
      ucp_version: "2.1"
      dtr_version: "2.2"
      docker_image: "docker/ucp:2.1.4"
  -
    scope:
      path: "datacenter/ucp/2.0"
    values:
      hide_from_sitemap: true
      ucp_version: "2.0"
      dtr_version: "2.1"
      docker_image: "docker/ucp:2.0.3"
  -
    scope:
      path: "datacenter/ucp/1.1"
    values:
      hide_from_sitemap: true
      ucp_version: "1.1"
      dtr_version: "2.0"
  -
    scope:
      path: "apidocs/v1.3.3"
    values:
      hide_from_sitemap: true
  -
    scope:
      path: "apidocs/v1.4.0"
    values:
      hide_from_sitemap: true
  -
    scope:
      path: "apidocs/v2.0.0"
    values:
      hide_from_sitemap: true
  -
    scope:
      path: "apidocs/v2.0.1"
    values:
      hide_from_sitemap: true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
