name: Docker Documentation
markdown: kramdown
kramdown:
  input: GFM
  gfm_quirks: [paragraph_end, no_auto_typographic]
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  toc_levels: 2..3
incremental: false
permalink: pretty
safe: false
lsi: false
url: https://docs.docker.com

# Component versions -- address like site.docker_ce_version
# You can't have - characters in these for non-YAML reasons

# TO USE ME:
# jekyll serve --incremental --config _config_authoring.yml

latest_engine_api_version: "1.39"
docker_ce_version: "18.09"
docker_ee_version: "18.09"
compose_version: "1.24.1"
compose_file_v3: "3.7"
compose_file_v2: "2.4"
machine_version: "0.16.0"
distribution_version: "2.6"
dtr_version: "2.6"
ucp_version: "3.1"

ucp_versions:
  - version: "3.1"
    path: /ee/ucp/
    latest: true
  - version: "3.0"
    path: /datacenter/ucp/3.0/guides/
  - version: "2.2"
    path: /datacenter/ucp/2.2/guides/
  - version: "2.1"
    path: /datacenter/ucp/2.1/guides/
  - version: "2.0"
    path: /datacenter/ucp/2.0/guides/
  - version: "1.1"
    path: /datacenter/ucp/1.1/overview/

dtr_versions:
  - version: "2.6"
    path: /ee/dtr/
    latest: true
  - version: "2.5"
    path: /datacenter/dtr/2.5/guides/
  - version: "2.4"
    path: /datacenter/dtr/2.4/guides/
  - version: "2.3"
    path: /datacenter/dtr/2.3/guides/
  - version: "2.2"
    path: /datacenter/dtr/2.2/guides/
  - version: "2.1"
    path: /datacenter/dtr/2.1/guides/
  - version: "2.0"
    path: /datacenter/dtr/2.0/

tablabels:
  dee-2.0: Docker Enterprise Edition 2.0
  ucp-3.0: Universal Control Plane 3.0
  ucp-2.2: Universal Control Plane 2.2
  dtr-2.5: Docker Trusted Registry 2.5
  dtr-2.4: Docker Trusted Registry 2.4
  engine-17.06: Docker EE Engine 17.06
  engine-17.03: Docker EE Engine 17.03
  docker-cli-linux: Docker CLI on Mac/Linux
  docker-cli-win: Docker CLI on Windows
  kubectl: Kubernetes CLI
  cli: CLI

collections:
  samples:
    output: true

plugins:
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      toc_min: 2
      toc_max: 3
      tree: true
  - scope:
      path: "install"
    values:
      win_latest_build: "docker-18.09.1"
  - scope:
      path: "datacenter"
    values:
      enterprise: true
  - scope:
      path: "ee/dtr"
    values:
      dtr_org: "docker"
      dtr_repo: "dtr"
      dtr_version: "2.6.1"
  - scope:
      path: "datacenter/dtr/2.5"
    values:
      hide_from_sitemap: true
      dtr_org: "docker"
      dtr_repo: "dtr"
      dtr_version: "2.5.7"
  - scope:
      path: "datacenter/dtr/2.4"
    values:
      hide_from_sitemap: true
      dtr_org: "docker"
      dtr_repo: "dtr"
      dtr_version: "2.4.8"
  - scope:
      path: "datacenter/dtr/2.3"
    values:
      hide_from_sitemap: true
      dtr_org: "docker"
      dtr_repo: "dtr"
      dtr_version: "2.3.10"
  - scope:
      path: "datacenter/dtr/2.2"
    values:
      ucp_version: "2.1"
      dtr_version: "2.2"
      docker_image: "docker/dtr:2.2.11"
  - scope:
      path: "datacenter/dtr/2.1"
    values:
      ucp_version: "2.0"
      dtr_version: "2.1"
  - scope:
      path: "datacenter/dtr/2.0"
    values:
      ucp_version: "1.1"
      dtr_version: "2.0"
  - scope:
      path: "ee/ucp"
    values:
      ucp_org: "docker"
      ucp_repo: "ucp"
      ucp_version: "3.1.2"
  - scope: # This is a bit of a hack for the get-support.md topic.
      path: "ee"
    values:
      ucp_org: "docker"
      ucp_repo: "ucp"
      dtr_repo: "dtr"
      ucp_version: "3.1.2"
      dtr_version: "2.6.1"
  - scope:
      path: "datacenter/ucp/3.0"
    values:
      hide_from_sitemap: true
      ucp_org: "docker"
      ucp_repo: "ucp"
      ucp_version: "3.0.8"
  - scope:
      path: "datacenter/ucp/2.2"
    values:
      hide_from_sitemap: true
      ucp_org: "docker"
      ucp_repo: "ucp"
      ucp_version: "2.2.15"
  - scope:
      path: "datacenter/ucp/2.1"
    values:
      hide_from_sitemap: true
      ucp_version: "2.1"
      dtr_version: "2.2"
      docker_image: "docker/ucp:2.1.8"
  - scope:
      path: "datacenter/ucp/2.0"
    values:
      hide_from_sitemap: true
      ucp_version: "2.0"
      dtr_version: "2.1"
      docker_image: "docker/ucp:2.0.4"
  - scope:
      path: "datacenter/ucp/1.1"
    values:
      hide_from_sitemap: true
      ucp_version: "1.1"
      dtr_version: "2.0"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
