name: Docker Documentation
markdown: kramdown
kramdown:
  input: GFM
  gfm_quirks: [paragraph_end, no_auto_typographic]
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  toc_levels: 2..3
incremental: true
permalink: pretty
safe: false
lsi: false
exclude: ["_scripts", "tests", "apidocs/layouts", "Gemfile", "hooks", "index.html", "404.html"]

# Google Analytics, etc.
# TODO these should only be set when building for production, or passed as an environment variable when building
google_analytics: GTM-WL2QLG5


# Component versions -- address like site.docker_ce_version
# You can't have - characters in these for non-YAML reasons

latest_engine_api_version: "1.40"
docker_ce_version: "19.03"
compose_version: "1.26.2"
compose_file_v3: "3.8"
compose_file_v2: "2.4"
machine_version: "0.16.0"
distribution_version: "2.7"

collections:
  samples:
    output: true

plugins:
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      toc_min: 2
      toc_max: 3
      tree: true
  # Hide Enterprise content from sitemap, and include banner in stubs that
  # content has moved to mirantis
  - scope:
      path: "datacenter"
    values:
      enterprise: true
      hide_from_sitemap: true
      title: Docker Enterprise moved to Mirantis
  - scope:
      path: "ee"
    values:
      enterprise: true
      hide_from_sitemap: true
      title: Docker Enterprise moved to Mirantis

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
