name: netlify action
description: handle the integration with netlify
inputs:
  netlify_token:
    description: Access token for netlify
    required: true
  site_name:
    description: Site name on netlify
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.netlify_token }}
    - ${{ inputs.site_name }}
